### ISSUE TITLE
Dependencies of sideband on *adapter_rstn

### ISSUE THREAD

**Issue by pkhanhesi** [intel/aib-phy-hardware#29]
Hi,
As the AIB spec, sideband FSM should not be constrained by *adapter_rstn and *mac_rdy.
However, current model implementation having this constraint. 
Would you please consider to fix this?

file: aib_channel.v

![model](https://user-images.githubusercontent.com/52446028/66982749-0bee8680-f0e1-11e9-9f27-eefa8dc0af27.png)

NOTE: 
-	ms_adapter_rstn is ns_adapter_rstn
-	adapter_rsti is fs_adapter_rstn

Thanks

**Comment by dkehlet** [comment]
Note: this file aib_channel.v is in the directory aib-phy-hardware/rtl.  It is a bus functional model of an AIB, not the design files that are in folder aib-phy-hardware/aib_lib.  The bug is still a bug.

"Per AIB spec, the shift register should be a free running as soon as CONF_DONE is released or HARD_RESET (i_adpt_hard_rst_n) is released.
1. Use this signal as reset to shift register.    
2. Make sure that LOAD/DATA/CLK to support SSR are functional even when ns/fs_adapter_rstn is LO.
"

**Comment by xinyang2k** [comment]
Thanks for the feedback. The issue has been fixed in 10/23/2019.
Files the modified are:
rtl/aib_channel.v
rtl/aib_sr_sl.v
rtl/aib_sr_ms.v
rtl/aib_ioring

**Comment by pkhanhesi** [comment]
Hi, 
This seem not resolved yet, because the conf_done is now depend on *adapter_rstn because ms_reset_n_sync is created from adpt_rstn which is eventually from *adapter_rstn.

File aib_channel.v
 ![1](https://user-images.githubusercontent.com/52446028/67475982-59d73180-f681-11e9-864d-ae4e70a75ef8.png)

File aib_sm.v
![2](https://user-images.githubusercontent.com/52446028/67476001-65c2f380-f681-11e9-9a51-0ba99d0d3f0c.png)

 Please consider to fix.
Best regards,
